// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjMP0fap5IQ2tA2JdMZMr9fngAL1oiF9I',
    appId: '1:574310982609:web:557c047d4ad9fe4fde76f0',
    messagingSenderId: '574310982609',
    projectId: 'yogividamobile',
    authDomain: 'yogividamobile.firebaseapp.com',
    storageBucket: 'yogividamobile.firebasestorage.app',
    measurementId: 'G-EDMF4GHF4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2N3RLnZaLMgCrjS-9CIY7BSt9vizQqI',
    appId: '1:574310982609:android:cf8f59ba78c53db0de76f0',
    messagingSenderId: '574310982609',
    projectId: 'yogividamobile',
    storageBucket: 'yogividamobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGdq8S0FpZ9APtU7C-CnKO5mnDZDYdbpk',
    appId: '1:574310982609:ios:a261b43e0615a713de76f0',
    messagingSenderId: '574310982609',
    projectId: 'yogividamobile',
    storageBucket: 'yogividamobile.firebasestorage.app',
    iosBundleId: 'com.example.yogivida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGdq8S0FpZ9APtU7C-CnKO5mnDZDYdbpk',
    appId: '1:574310982609:ios:a261b43e0615a713de76f0',
    messagingSenderId: '574310982609',
    projectId: 'yogividamobile',
    storageBucket: 'yogividamobile.firebasestorage.app',
    iosBundleId: 'com.example.yogivida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjMP0fap5IQ2tA2JdMZMr9fngAL1oiF9I',
    appId: '1:574310982609:web:c9a9783a39b7a446de76f0',
    messagingSenderId: '574310982609',
    projectId: 'yogividamobile',
    authDomain: 'yogividamobile.firebaseapp.com',
    storageBucket: 'yogividamobile.firebasestorage.app',
    measurementId: 'G-HSKX1W2DMJ',
  );
}
